##
## EPITECH PROJECT, 2023
## Makefile
## File description:
## Makefile
##

all:
	@$(MAKE) -s -C generator all
	@$(MAKE) -s -C solver all

clean:
	@$(MAKE) -s -C generator clean
	@$(MAKE) -s -C solver clean

fclean:
	@$(MAKE) -s -C generator fclean
	@$(MAKE) -s -C solver fclean

re:
	@$(MAKE) -s -C generator re
	@$(MAKE) -s -C solver re

.PHONY: all clean fclean re
