##
## EPITECH PROJECT, 2023
## Makefile
## File description:
## Makefile
##

all:
	@$(MAKE) -s -C antman
	@$(MAKE) -s -C giantman

clean:
	@$(MAKE) -s -C antman clean
	@$(MAKE) -s -C giantman clean

fclean:
	@$(MAKE) -s -C antman fclean
	@$(MAKE) -s -C giantman fclean

re:
	@$(MAKE) -s -C antman re
	@$(MAKE) -s -C giantman re
